// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web.Models
{
    public partial class Contrato
    {
        public Contrato()
        {
            ValorIndicadorContrato = new HashSet<ValorIndicadorContrato>();
        }

        public int Id { get; set; }
        public int CantidadCamiones { get; set; }
        public double CantidadEnToneladas { get; set; }
        public bool Cumplido { get; set; }
        public DateTime FechaEmision { get; set; }
        public DateTime FechaLimite { get; set; }
        public bool MedidoEnToneladas { get; set; }
        public string MetodoDePago { get; set; }
        public int Numero { get; set; }
        public double PrecioTonelada { get; set; }
        public int ProveedorId { get; set; }
        public int GranoId { get; set; }
        public int EmpleadoId { get; set; }

        public virtual Empleado Empleado { get; set; }
        public virtual Grano Grano { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<ValorIndicadorContrato> ValorIndicadorContrato { get; set; }
    }
}