// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web.Models
{
    public partial class Direccion
    {
        public Direccion()
        {
            Proveedor = new HashSet<Proveedor>();
        }

        public int Id { get; set; }
        public int Altura { get; set; }
        public string Calle { get; set; }
        public string Departamento { get; set; }
        public int Numero { get; set; }
        public int LocalidadId { get; set; }

        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}