// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web.Models
{
    public partial class Empleado
    {
        public Empleado()
        {
            Contrato = new HashSet<Contrato>();
        }

        public int Id { get; set; }
        public string Apellido { get; set; }
        public int Cuil { get; set; }
        public int Dni { get; set; }
        public int Legajo { get; set; }
        public string Nombre { get; set; }
        public int Telefono { get; set; }
        public string Turno { get; set; }

        public virtual ICollection<Contrato> Contrato { get; set; }
    }
}