// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web.Models
{
    public partial class IndicadorCalidad
    {
        public IndicadorCalidad()
        {
            ValorIndicadorContrato = new HashSet<ValorIndicadorContrato>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<ValorIndicadorContrato> ValorIndicadorContrato { get; set; }
    }
}