// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web.Models
{
    public partial class Localidad
    {
        public Localidad()
        {
            Direccion = new HashSet<Direccion>();
        }

        public int Id { get; set; }
        public int CodigoPostal { get; set; }
        public string Nombre { get; set; }
        public int ProvinciaId { get; set; }

        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
    }
}