// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web.Models
{
    public partial class Provincia
    {
        public Provincia()
        {
            Localidad = new HashSet<Localidad>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public int PaisId { get; set; }

        public virtual Pais Pais { get; set; }
        public virtual ICollection<Localidad> Localidad { get; set; }
    }
}