// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web.Models
{
    public partial class Proveedor
    {
        public Proveedor()
        {
            Contrato = new HashSet<Contrato>();
        }

        public int Id { get; set; }
        public string Cuit { get; set; }
        public string Email { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public int Telefono { get; set; }
        public int DireccionId { get; set; }

        public virtual Direccion Direccion { get; set; }
        public virtual ICollection<Contrato> Contrato { get; set; }
    }
}