// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web.Models
{
    public partial class TipoGrano
    {
        public TipoGrano()
        {
            Grano = new HashSet<Grano>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Grano> Grano { get; set; }
    }
}